name: build matrix demo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.6, 3.10]
    steps:
    - uses: actions/checkout@v2 # Checking out the repo
    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        PYTHON_IMAGE_VERSION: ${{ matrix.version }}
        command: install -d # Install all dependencies, including development ones


